steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/hike-agentic-playground/mcp-cloud-run-deployments/ugc-flow:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/hike-agentic-playground/mcp-cloud-run-deployments/ugc-flow:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/hike-agentic-playground/mcp-cloud-run-deployments/ugc-flow']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ngr-ugc
      - '--image=us-central1-docker.pkg.dev/hike-agentic-playground/mcp-cloud-run-deployments/ugc-flow:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--project=hike-agentic-playground'

images:
  - 'us-central1-docker.pkg.dev/hike-agentic-playground/mcp-cloud-run-deployments/ugc-flow:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/hike-agentic-playground/mcp-cloud-run-deployments/ugc-flow:latest'

options:
  logging: CLOUD_LOGGING_ONLY
